### PR TITLE
Add items and vehicle parts to the flag screen

### PR DESCRIPTION
**Pull request by CalKerethi**
Adds the feature requested in #17. When you open up a flag, every item and vehicle part that has it is listed. Also adds Flags to the links on the home screen.

The code was really easy to pick up and edit, even for someone who hadn't used the technologies before! Hopefully my changes are all in good order.

### CODE REVIEW

**Review by nornagon — APPROVED** [review]
Looks good to me, thanks for the contribution! Glad you found it easy to work with :)

**Comment by nornagon** [comment]
This is now live!

**Comment by CalKerethi** [comment]
Awesome! I realize now that I should have considered adding vehicle parts to qualities too, since I did it for flags. I'll probably make a few more small pull requests as I think of other things.

**Comment by nornagon** [comment]
Sounds good :)

**Pull request merged**
