### PR TITLE
japanese

### PR DESCRIPTION
**Pull request by nornagon**
hi @lispcoc! Just discovered your branch w/ Japanese support and I think that's so cool!! I'd love to get something like this merged into the main branch--see https://github.com/nornagon/cdda-guide/issues/42.

Would you be interested in working on this further?

### CODE REVIEW

**Comment by lispcoc** [comment]
I'm too busy to write new code, but I think it's good. Please merge my code.

**Comment by nornagon** [comment]
@lispcoc alright, I'll take a look. I'll need to expand it further to:

1. Allow the user to select a language,
2. Automatically generate the language files from the game source (see https://github.com/nornagon/cdda-data/blob/main/pull-data.sh for how I do this for JSON files; I'll expand that code to also generate language json)

One thing I'm not sure about: how did you generate the `ja.json` file in https://github.com/lispcoc/cdda-lang-json?

**Comment by nornagon** [comment]
Aha, maybe this? https://www.npmjs.com/package/po2json

**Comment by lispcoc** [comment]
I don't remember but maybe it is

**Comment by nornagon** [comment]
I ended up doing this a different way in order to correctly handle pluralization in other languages. See https://github.com/nornagon/cdda-guide/commit/978eb7fa6f0f744065b396b665007f3c88acffdf.

**Pull request closed without merging**
